### ISSUE TITLE
Failure on Ubuntu 22.04

### ISSUE THREAD

**Issue by adamryczkowski** [binpash/try#62] opened 2023-06-25 09:19 UTC
I've tried the following (as normal user) on my Ubuntu 22.04 64bit machine:

```
$ bash -x ./try pip install ipython
+ TRY_VERSION=0.1.0
+ NO_COMMIT=interactive
+ getopts :yvnD: opt
+ shift 0
+ '[' 3 -eq 0 ']'
+ case "$1" in
+ try pip install ipython
+ START_DIR=/home/Adama-docs/Adam/linux/tmp/try
+ '[' '' ']'
++ mktemp -d
+ SANDBOX_DIR=/tmp/tmp.zehcnpM68I
+ export SANDBOX_DIR
+ mkdir -p /tmp/tmp.zehcnpM68I/upperdir /tmp/tmp.zehcnpM68I/workdir /tmp/tmp.zehcnpM68I/temproot
+ for top_dir in /*
+ '[' -d /bin ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//bin /tmp/tmp.zehcnpM68I/workdir//bin /tmp/tmp.zehcnpM68I/temproot//bin
+ for top_dir in /*
+ '[' -d /boot ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//boot /tmp/tmp.zehcnpM68I/workdir//boot /tmp/tmp.zehcnpM68I/temproot//boot
+ for top_dir in /*
+ '[' -d /dev ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//dev /tmp/tmp.zehcnpM68I/workdir//dev /tmp/tmp.zehcnpM68I/temproot//dev
+ for top_dir in /*
+ '[' -d /etc ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//etc /tmp/tmp.zehcnpM68I/workdir//etc /tmp/tmp.zehcnpM68I/temproot//etc
+ for top_dir in /*
+ '[' -d /home ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//home /tmp/tmp.zehcnpM68I/workdir//home /tmp/tmp.zehcnpM68I/temproot//home
+ for top_dir in /*
+ '[' -d /lib ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//lib /tmp/tmp.zehcnpM68I/workdir//lib /tmp/tmp.zehcnpM68I/temproot//lib
+ for top_dir in /*
+ '[' -d /lib32 ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//lib32 /tmp/tmp.zehcnpM68I/workdir//lib32 /tmp/tmp.zehcnpM68I/temproot//lib32
+ for top_dir in /*
+ '[' -d /lib64 ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//lib64 /tmp/tmp.zehcnpM68I/workdir//lib64 /tmp/tmp.zehcnpM68I/temproot//lib64
+ for top_dir in /*
+ '[' -d /libx32 ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//libx32 /tmp/tmp.zehcnpM68I/workdir//libx32 /tmp/tmp.zehcnpM68I/temproot//libx32
+ for top_dir in /*
+ '[' -d /media ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//media /tmp/tmp.zehcnpM68I/workdir//media /tmp/tmp.zehcnpM68I/temproot//media
+ for top_dir in /*
+ '[' -d /mnt ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//mnt /tmp/tmp.zehcnpM68I/workdir//mnt /tmp/tmp.zehcnpM68I/temproot//mnt
+ for top_dir in /*
+ '[' -d /opt ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//opt /tmp/tmp.zehcnpM68I/workdir//opt /tmp/tmp.zehcnpM68I/temproot//opt
+ for top_dir in /*
+ '[' -d /Passwords2.kdbx ']'
+ for top_dir in /*
+ '[' -d /photoprism ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//photoprism /tmp/tmp.zehcnpM68I/workdir//photoprism /tmp/tmp.zehcnpM68I/temproot//photoprism
+ for top_dir in /*
+ '[' -d /proc ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//proc /tmp/tmp.zehcnpM68I/workdir//proc /tmp/tmp.zehcnpM68I/temproot//proc
+ for top_dir in /*
+ '[' -d /root ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//root /tmp/tmp.zehcnpM68I/workdir//root /tmp/tmp.zehcnpM68I/temproot//root
+ for top_dir in /*
+ '[' -d /run ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//run /tmp/tmp.zehcnpM68I/workdir//run /tmp/tmp.zehcnpM68I/temproot//run
+ for top_dir in /*
+ '[' -d /sbin ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//sbin /tmp/tmp.zehcnpM68I/workdir//sbin /tmp/tmp.zehcnpM68I/temproot//sbin
+ for top_dir in /*
+ '[' -d /snap ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//snap /tmp/tmp.zehcnpM68I/workdir//snap /tmp/tmp.zehcnpM68I/temproot//snap
+ for top_dir in /*
+ '[' -d /srv ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//srv /tmp/tmp.zehcnpM68I/workdir//srv /tmp/tmp.zehcnpM68I/temproot//srv
+ for top_dir in /*
+ '[' -d /@swap ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//@swap /tmp/tmp.zehcnpM68I/workdir//@swap /tmp/tmp.zehcnpM68I/temproot//@swap
+ for top_dir in /*
+ '[' -d /swap ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//swap /tmp/tmp.zehcnpM68I/workdir//swap /tmp/tmp.zehcnpM68I/temproot//swap
+ for top_dir in /*
+ '[' -d /swap.img ']'
+ for top_dir in /*
+ '[' -d /sys ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//sys /tmp/tmp.zehcnpM68I/workdir//sys /tmp/tmp.zehcnpM68I/temproot//sys
+ for top_dir in /*
+ '[' -d /tmp ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//tmp /tmp/tmp.zehcnpM68I/workdir//tmp /tmp/tmp.zehcnpM68I/temproot//tmp
+ for top_dir in /*
+ '[' -d /usr ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//usr /tmp/tmp.zehcnpM68I/workdir//usr /tmp/tmp.zehcnpM68I/temproot//usr
+ for top_dir in /*
+ '[' -d /var ']'
+ mkdir /tmp/tmp.zehcnpM68I/upperdir//var /tmp/tmp.zehcnpM68I/workdir//var /tmp/tmp.zehcnpM68I/temproot//var
++ mktemp
+ mount_and_execute=/tmp/tmp.vu7KwDCiXR
++ mktemp
+ export chroot_executable=/tmp/tmp.o2GNp8OpGq
+ chroot_executable=/tmp/tmp.o2GNp8OpGq
++ mktemp
+ export try_mount_log=/tmp/tmp.HYUBzRN8rm
+ try_mount_log=/tmp/tmp.HYUBzRN8rm
+ cat
+ cat
+ chmod +x /tmp/tmp.vu7KwDCiXR /tmp/tmp.o2GNp8OpGq
+ unshare --mount --map-root-user --user --pid --fork /tmp/tmp.vu7KwDCiXR
Warning: Failed mounting /home as an overlay, see /tmp/tmp.HYUBzRN8rm
Warning: Failed mounting /media as an overlay, see /tmp/tmp.HYUBzRN8rm
Warning: Failed mounting /snap as an overlay, see /tmp/tmp.HYUBzRN8rm
Warning: Failed mounting /var as an overlay, see /tmp/tmp.HYUBzRN8rm
Warning: Failed mounting /run/user/1000/doc as an overlay, see /tmp/tmp.HYUBzRN8rm
Warning: Failed mounting /snap/acrordrdc/62 as an overlay, see /tmp/tmp.HYUBzRN8rm
Warning: Failed mounting /snap/bare/5 as an overlay, see /tmp/tmp.HYUBzRN8rm
...
Warning: Failed mounting /boot as an overlay, see /tmp/tmp.HYUBzRN8rm
Warning: Failed mounting /boot/efi as an overlay, see /tmp/tmp.HYUBzRN8rm
Warning: Failed mounting /var/lib/docker/btrfs as an overlay, see /tmp/tmp.HYUBzRN8rm
Warning: Failed mounting /home/adam as an overlay, see /tmp/tmp.HYUBzRN8rm
Warning: Failed mounting /home/Adama-docs as an overlay, see /tmp/tmp.HYUBzRN8rm
/tmp/tmp.o2GNp8OpGq: line 4: cd: /home/Adama-docs/Adam/linux/tmp/try: No such file or directory
+ exitcode=1
+ case "$NO_COMMIT" in
+ summary /tmp/tmp.zehcnpM68I
+ '[' -d /tmp/tmp.zehcnpM68I ']'
+ '[' -d /tmp/tmp.zehcnpM68I/upperdir ']'
++ find /tmp/tmp.zehcnpM68I/upperdir/ -type f -or '(' -type c -size 0 ')'
++ ignore_changes
++ grep -v -e .rkr -e Rikerfile
+ changed_files=
+ '[' -z '' ']'
+ return 1
+ '[' 1 -eq 0 ']'
+ exit 1

/tmp/tmp.RqaXJrG4E1: line 4: cd: /home/Adama-docs/Adam/linux/tmp/try: No such file or directory
```

It failed without a comprehensive error message (folder `/home/Adama-docs/Adam/linux/tmp/try` obviously exists, as this is the place the repository was cloned).

**Comment by kubrickfr** [comment] 2023-06-25 09:32
Probably a duplicate of #53 ?

**Comment by adamryczkowski** [comment] 2023-06-25 15:26
Probably. :-) There are differences, like the `cd` command displayed at the end of warnings.

**Comment by ericzty** [comment] 2023-06-25 15:32
Could you please send the contents of /tmp/tmp.HYUBzRN8rm

Seems like a duplicate of #19 as there is nested mounts in your /home

**Comment by ericzty** [comment] 2023-06-25 18:42
could you try with branch nested-mount (need to install mergerfs aswell)
 If you don't like mergerfs, you can install unionfs-fuse and change the two appearances of mergerfs to unionfs (L70, L83)

**Comment by ErrorNoInternet** [comment] 2023-06-26 05:48
It finally works on Fedora 38 with the nested-mount branch (mergerfs from [here](https://copr.fedorainfracloud.org/coprs/errornointernet/mergerfs/)).

**Comment by ericzty** [comment] 2023-06-26 22:25
Great, closing as duplicate of #19 then.
If the issue doesn't resolve with nested-mount, please reopen the issue.

**Closed by ericzty** 2023-06-26 22:25 UTC
