### ISSUE TITLE
Running commands that access the network

### ISSUE THREAD

**Issue by gliargovas** [binpash/try#12] opened 2023-06-04 07:30 UTC
It seems that `try` blocks any kind of network access:
```
$ try "ping -c3 www.google.com"
mount: /tmp/tmp.l06qs0JdDT/temproot/boot: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
mount: /tmp/tmp.l06qs0JdDT/temproot/var: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
ping: www.google.com: Temporary failure in name resolution
```
```
$ try curl www.google.com
mount: /tmp/tmp.8hpad1vI2s/temproot/boot: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
mount: /tmp/tmp.8hpad1vI2s/temproot/var: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
curl: (6) Could not resolve host: www.google.com
```
Despite this, `unshare --mount --map-root-user --user --pid --fork curl www.google.com` runs successfully.

Also, double checked that we are not unsharing the network namespace anywhere.

**Comment by angelhof** [comment] 2023-06-05 15:42
On cloudlab this works properly. Which machine are you trying this on? Also, what is the output when not using try for the same commands.

**Comment by gliargovas** [comment] 2023-06-19 22:39
I only get this issue when running on `Ubuntu 22`. It should have to do with the kernel version.

**Comment by angelhof** [comment] 2023-06-19 22:44
Oh, I see, maybe @ericzty could help you to run it on a specific kernel version to figure out exactly what the problem is and when it happens?

**Comment by ericzty** [comment] 2023-06-20 01:27
The issue is with the DNS, since /etc/resolv.conf is a link on that ubuntu system (/run/systemd/resolve/stub-resolv.conf), when in Overlayfs the link broke. The issue can be fixed by adding the following to the innermost shell script in try.
```
rm /etc/resolv.conf
echo "nameserver 1.1.1.1" > /etc/resolv.conf
```

Another solution that [cbuildrt](https://github.com/managarm/cbuildrt/blob/2b6a9a7907640dcfe87da578ab27202ac009a674/src/main.rs#L106) used is to mount the resolv.conf over from the host filesystem, that is probably a better approach.

**Comment by angelhof** [comment] 2023-06-20 20:16
Closing this issue since it has nothing to do with the network

**Closed by angelhof** 2023-06-20 20:16 UTC
