### ISSUE TITLE
libreadline error

### ISSUE THREAD

**Issue by franalbani** [binpash/try#50] opened 2023-06-24 22:21 UTC
```
$ try ls
/bin/bash: error while loading shared libraries: libreadline.so.8: cannot open shared object file: No such file or directory
```

I'm in an up-to-date Arch Linux.

**Comment by ericzty** [comment] 2023-06-24 23:12
Could you please provide the output of `pacman -Q readline`, and the
output of `mount` (outside of try).

I can not reproduce this on my Arch VM, but I suspect it may be
caused by a weird `/usr` mount (where libreadline.so is stored)

-- 
Eric

**Comment by franalbani** [comment] 2023-06-24 23:32
> Could you please provide the output of `pacman -Q readline`, and the output of `mount` (outside of try). I can not reproduce this on my Arch VM, but I suspect it may be caused by a weird `/usr` mount (where libreadline.so is stored)
> […](#)
> -- Eric

```console
$ pacman -Q readline
readline 8.2.001-2
```

`/usr` is an lvm volume independent from `/`. I don't think this is related (as it would break a lot of other things, which is not).

**Comment by ericzty** [comment] 2023-06-24 23:46
On Sat Jun 24, 2023 at 7:32 PM EDT, Francisco Albani wrote:
> `/usr` is an lvm volume independent from `/`. I don't think this is related (as it would break a lot of other things, which is not).

My idea is that in `try`, the `/usr` is not being properly mounted. 

Could you send the output of `mount` so we can see what exactly the
mount structure is like, it could be related to #19. Although, on my
Debian+LVM setup with /home and / as separate LVM Logical Volumes, try
works fine.

**Comment by franalbani** [comment] 2023-06-25 01:07
> On Sat Jun 24, 2023 at 7:32 PM EDT, Francisco Albani wrote: `/usr` is an lvm volume independent from `/`. I don't think this is related (as it would break a lot of other things, which is not).
> My idea is that in `try`, the `/usr` is not being properly mounted. Could you send the output of `mount` so we can see what exactly the mount structure is like, it could be related to #19. Although, on my Debian+LVM setup with /home and / as separate LVM Logical Volumes, try works fine.

```console
$ mount | grep usr
/dev/mapper/volgroup-usr on /usr type ext4 (rw,relatime)
```

**Comment by ericzty** [comment] 2023-06-25 01:41
With the following setup
```console
***@***.***:~/try$ mount | grep -E "home|root"
/dev/mapper/vg0-lv--root on / type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/vg0-lv--home on /home type ext4 (rw,relatime)
```

It seems like LVM was able to be mounted, are you on the latest `main`
branch, the issue should be fixed after this commit.
https://github.com/binpash/try/commit/3ecf1fd58bb8cf590603f8d73c15a40a7a5dcb36

**Comment by franalbani** [comment] 2023-06-25 02:17
Now I tried with the latest:

```console
$ try ls
Warning: Failed mounting /run/user/1000/doc as an overlay, see /tmp/tmp.v5wSonVWQN
Warning: Failed mounting /var as an overlay, see /tmp/tmp.v5wSonVWQN
Warning: Failed mounting /var/lib/docker as an overlay, see /tmp/tmp.v5wSonVWQN
Warning: Failed mounting /home as an overlay, see /tmp/tmp.v5wSonVWQN
Warning: Failed mounting /home/fran/archive as an overlay, see /tmp/tmp.v5wSonVWQN
Warning: Failed mounting /boot as an overlay, see /tmp/tmp.v5wSonVWQN
Warning: Failed mounting /mnt as an overlay, see /tmp/tmp.v5wSonVWQN
/tmp/tmp.adLjVGW4CX: line 4: cd: /home/fran: No such file or directory

$ cat /tmp/tmp.v5wSonVWQN
mount: /tmp/tmp.n3NWTp7qEt/temproot/run/user/1000/doc: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
mount: /tmp/tmp.n3NWTp7qEt/temproot/var: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
mount: /tmp/tmp.n3NWTp7qEt/temproot/var/lib/docker: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
mount: /tmp/tmp.n3NWTp7qEt/temproot/home: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
mount: /tmp/tmp.n3NWTp7qEt/temproot/home/fran/archive: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
mount: /tmp/tmp.n3NWTp7qEt/temproot/boot: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
mount: /tmp/tmp.n3NWTp7qEt/temproot/mnt: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
```

**Comment by ericzty** [comment] 2023-06-25 02:30
> Warning: Failed mounting /home/fran/archive as an overlay, see /tmp/tmp.v5wSonVWQN
That's related to #19, if you unmount archive, try should be able to
mount /home and the rest should work.

**Comment by ericzty** [comment] 2023-06-25 02:31
To confirm, could you please see if you see the following in `dmesg`

```console
[308798.929868] overlayfs: failed to set xattr on upper
[308798.929873] overlayfs: try mounting with 'userxattr' option
[308798.929883] overlayfs: failed to clone lowerpath
```

**Comment by franalbani** [comment] 2023-06-25 02:54
> Warning: Failed mounting /home/fran/archive as an overlay, see /tmp/tmp.v5wSonVWQN
> That's related to #19, if you unmount archive, try should be able to mount /home and the rest should work.
OK. I cannot unmount `archive` right now. I will try later. Thanks!

> To confirm, could you please see if you see the following in `dmesg` ```console [308798.929868] overlayfs: failed to set xattr on upper [308798.929873] overlayfs: try mounting with 'userxattr' option [308798.929883] overlayfs: failed to clone lowerpath ```

I do.

Do you have plans to support this kind of setup?

**Comment by ericzty** [comment] 2023-06-25 03:03
> Do you have plans to support this kind of setup?

Yes, that is one of my top issues to investigate, as it affects a lot of
setups. Hopefully it is something that's do-able.

**Closed** 2023-06-25 03:40 UTC
